### ISSUE TITLE
Generate translation for "Sag mal"

### ISSUE THREAD

**Issue by Entkenntnis** [Entkenntnis/htw#11]
We have a placeholder right now, add translated file.

Note: File size should be around ~10MB with reasonable quality.

**Comment by virus-rpi** [comment]
Added translation in commit [d1aa006e3e1a0b0de9adfa2ad58357571a55ea1d](https://github.com/Entkenntnis/htw/commit/d1aa006e3e1a0b0de9adfa2ad58357571a55ea1d) (Size: 6.78 MB)
